// <auto-generated />
// <copyright>Copyright (c) Microsoft Corporation. All rights reserved.</copyright>

using Microsoft.CommonSchema.Services.Logging;
using Microsoft.CommonSchema.Services.ServiceFabricContainer;

namespace Microsoft.MarketplaceServices.ReferenceWorker
{
    /// <summary>
    /// SLL policy container class. Do not edit.
    /// </summary>
    public partial class Policies : PolicyRegistration
    {
        /// <summary>
        /// Gets the policy configuration for ServiceFabricContainer.
        /// </summary>
        public static ServiceFabricContainerPolicy ServiceFabricContainer
            => Single<ServiceFabricContainerPolicy>.Current;
    }
}
