# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: |
     **/SimpleNetCoreWebApp.csproj
     
    feedsToUse: config
    nugetConfigPath: .nuget/NuGet.config

#Your build pipeline references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: |
     **/SimpleNetCoreWebApp.sln
     
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: |
     **/SimpleNetCoreWebApp.csproj
     
    arguments: '-o $(Build.SourcesDirectory)/drop/$(BuildConfiguration)/Product/Dcc --configuration $(BuildConfiguration)'
    zipAfterPublish: false

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Ds3 Container'
    azureContainerRegistry: '{"loginServer":"NautilusEv2DemoACR.azurecr.io", "id" : "/subscriptions/9d9a1dd9-e1aa-4408-93c7-c7b6c5e85ee2/resourceGroups/NautilusEv2DemoRG/providers/Microsoft.ContainerRegistry/registries/NautilusEv2DemoACR"}'
    dockerFile: 'src/SimpleNetCoreWebApp/SimpleNetCoreWebApp/SimpleNetCoreWebApp.dockerfile'
    buildArguments: '--no-cache'
    imageName: 'NautilusEv2DemoACR.azurecr.io/dcc/dccfd:$(Build.DefinitionName)_$(Build.BuildNumber)'
    additionalImageTags: |
     $(Build.BuildId)
     $(Build.BuildNumber)
     
    includeSourceTags: true
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Ds3 Container'
    azureContainerRegistry: '{"loginServer":"NautilusEv2DemoACR.azurecr.io", "id" : "/subscriptions/9d9a1dd9-e1aa-4408-93c7-c7b6c5e85ee2/resourceGroups/NautilusEv2DemoRG/providers/Microsoft.ContainerRegistry/registries/NautilusEv2DemoACR"}'
    action: 'Push an image'
    imageName: 'NautilusEv2DemoACR.azurecr.io/dcc/dccfd:$(Build.DefinitionName)_$(Build.BuildNumber)'
    additionalImageTags: |
     $(Build.BuildId)
     $(Build.BuildNumber)
     
    includeSourceTags: true
    includeLatestTag: true
